services:
  skia_api_staging:
    image: ghcr.io/ariveratij40-lab/skia/skia-api:latest
    container_name: skia_api_staging
    restart: unless-stopped
    env_file:
      - .env.staging
    networks:
      - infra_network

  skia_web_staging:
    image: ghcr.io/ariveratij40-lab/skia/skia-web:latest
    container_name: skia_web_staging
    restart: unless-stopped
    env_file:
      - .env.staging
    networks:
      - infra_network

networks:
  infra_network:
    external: true
    name: infra_network
