name: Build & Push (GHCR)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      REGISTRY: ghcr.io
      OWNER: ${{ github.repository_owner }}
      SHA: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 🔐 Login GHCR
      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login $REGISTRY -u "${{ github.actor }}" --password-stdin

      # ==========================
      #        BACKEND
      # ==========================
      - name: Build skia-api
        run: |
          docker build \
            -t $REGISTRY/$OWNER/skia-api:latest \
            -t $REGISTRY/$OWNER/skia-api:$SHA \
            ./backend

      - name: Push skia-api
        run: |
          docker push $REGISTRY/$OWNER/skia-api:latest
          docker push $REGISTRY/$OWNER/skia-api:$SHA

      # ==========================
      #          WEB
      # ==========================
      - name: Build skia-web
        run: |
          docker build \
            -t $REGISTRY/$OWNER/skia-web:latest \
            -t $REGISTRY/$OWNER/skia-web:$SHA \
            ./web

      - name: Push skia-web
        run: |
          docker push $REGISTRY/$OWNER/skia-web:latest
          docker push $REGISTRY/$OWNER/skia-web:$SHA
